Repository TCastus/ASTUSbot, pull requests merged in 2020-12, with the labels that each got.

#41 Pot Très Confiné (décembre 2020)
  Dockerfile
  README.md
  cogs/__init__.py
  cogs/pot_tres_confine.py
  cogs/tgg/cog.py
  main.py
  myutils.py
  requirements.txt
Labels: enhancement

#43 🐛 Fix #42 and 🐳 docker
  .dockerignore
  Dockerfile
  cogs/tgg/cog.py
Labels: bug, enhancement

#44 Pot très confiné Décembre 2020
  cogs/pot_tres_confine.py
Labels: bug

#45 Adding meme command and update help command
  cogs/__init__.py
  cogs/help.py
  cogs/memes/__init__.py
  cogs/memes/assets/data.json
  cogs/memes/cog_meme.py
  embed.py
  main.py
Labels: documentation, enhancement
