Repository TCastus/ASTUSbot, pull requests merged in 2020-11, with the labels that each got.

#22 :heavy_plus_sign: Closes #21
  cogs/NSandSOALookup.py
  cogs/__init__.py
  cogs/help.py
  cogs/vendrediChill.py
  embed.py
  main.py
  myutils.py
Labels: enhancement

#23 Calendar
  cogs/__init__.py
  cogs/calendar/Assets/3TCA.ical
  cogs/calendar/Assets/4TC-GR2.ical
  cogs/calendar/__init__.py
  cogs/calendar/cog.py
  cogs/calendar/util.py
  main.py
  requirements.txt
Labels: enhancement

#24 Calendar
  cogs/calendar/Assets/3TC1.ical
  cogs/calendar/Assets/3TC2.ical
  cogs/calendar/Assets/3TC3.ical
  cogs/calendar/Assets/4TC1.ical
  cogs/calendar/Assets/4TC2.ical
  cogs/calendar/Assets/4TC3.ical
  cogs/calendar/Assets/4TCA.ical
  cogs/calendar/Assets/5TC1.ical
  cogs/calendar/Assets/5TC2.ical
  cogs/calendar/Assets/5TC3.ical
  cogs/calendar/cog.py
  cogs/calendar/util.py
Labels: enhancement

#25 Calendar
  cogs/calendar/Assets/3TC1.ical
  cogs/calendar/cog.py
  cogs/calendar/util.py
  cogs/help.py
  embed.py
  requirements.txt
Labels: enhancement

#28 Vendre chill🎉
  cogs/NSandSOALookup.py
  cogs/help.py
  cogs/infoFromIP.py
  cogs/international.py
  cogs/invitation.py
  cogs/newyear.py
  cogs/vendrediChill.py
  cogs/videoDiplomes.py
  embed.py
  main.py
Labels: enhancement

#30 Auto update calendar
  cogs/calendar/Assets/.gitkeep
  cogs/calendar/Assets/3TC1.ical
  cogs/calendar/Assets/3TC2.ical
  cogs/calendar/Assets/3TC3.ical
  cogs/calendar/Assets/3TCA.ical
  cogs/calendar/Assets/4TC1.ical
  cogs/calendar/Assets/4TC2.ical
  cogs/calendar/Assets/4TC3.ical
  cogs/calendar/Assets/4TCA.ical
  cogs/calendar/Assets/5TC1.ical
  cogs/calendar/Assets/5TC2.ical
  cogs/calendar/Assets/5TC3.ical
  cogs/calendar/cog.py
  cogs/calendar/util.py
  requirements.txt
Labels: enhancement

#31 Week calendar 📅
  .gitignore
  cogs/calendar/Assets/.gitkeep
  cogs/calendar/cog.py
  cogs/calendar/util.py
  requirements.txt
Labels: enhancement

#34 🎇 added ginny command #33
  cogs/__init__.py
  cogs/help.py
  cogs/tgg/Assets/Images/123189802_958646451289009_810186897783310569_n.jpg
  cogs/tgg/Assets/Images/123A33C9-89CC-48D5-BB86-B4B5DE078E93_1_105_c.jpeg
  cogs/tgg/Assets/Images/20200831_202738.jpg
  cogs/tgg/Assets/Images/7FB729CD-0CFD-470A-8C1F-602B899DE9A6_1_105_c.jpeg
  cogs/tgg/Assets/Images/9BC4EE30-22FC-434E-BF3F-4256AD41C262_1_105_c.jpeg
  cogs/tgg/Assets/Images/9E343422-91F6-4CC1-BD06-86E052D8491F.jpeg
  cogs/tgg/Assets/Images/D93ABBE8-1918-40D2-8459-79008F375E6B_1_105_c.jpeg
  cogs/tgg/Assets/Images/DSC_3708.JPG
  cogs/tgg/Assets/Images/DSC_3775.JPG
  cogs/tgg/Assets/Images/DSC_3818.JPG
  cogs/tgg/Assets/Images/DSC_3956.JPG
  cogs/tgg/Assets/Images/DSC_4015.JPG
  cogs/tgg/Assets/Images/DSC_4573.JPG
  cogs/tgg/Assets/Images/IMG_0639.PNG
  cogs/tgg/Assets/Images/IMG_0641.PNG
  cogs/tgg/Assets/Images/IMG_0642.PNG
  cogs/tgg/Assets/Images/IMG_1608-removebg-preview.png
  cogs/tgg/Assets/Images/IMG_4D5DD8F95DA1-1.jpeg
  cogs/tgg/Assets/Images/Screenshot 2020-11-12 at 10.03.16.png
  cogs/tgg/Assets/Images/Screenshot 2020-11-12 at 10.03.33.png
  cogs/tgg/Assets/Images/Screenshot 2020-11-12 at 13.47.15.png
  cogs/tgg/Assets/Quote.json
  cogs/tgg/__init__.py
  cogs/tgg/cog.py
  embed.py
  main.py
Labels: enhancement

#35 :hammer: refactor tgg command :fire:
  cogs/tgg/Assets/Images/123189802_958646451289009_810186897783310569_n.jpg
  cogs/tgg/Assets/Images/123A33C9-89CC-48D5-BB86-B4B5DE078E93_1_105_c.jpeg
  cogs/tgg/Assets/Images/20200831_202738.jpg
  cogs/tgg/Assets/Images/7FB729CD-0CFD-470A-8C1F-602B899DE9A6_1_105_c.jpeg
  cogs/tgg/Assets/Images/9BC4EE30-22FC-434E-BF3F-4256AD41C262_1_105_c.jpeg
  cogs/tgg/Assets/Images/9E343422-91F6-4CC1-BD06-86E052D8491F.jpeg
  cogs/tgg/Assets/Images/D93ABBE8-1918-40D2-8459-79008F375E6B_1_105_c.jpeg
  cogs/tgg/Assets/Images/DSC_3708.JPG
  cogs/tgg/Assets/Images/DSC_3775.JPG
  cogs/tgg/Assets/Images/DSC_3818.JPG
  cogs/tgg/Assets/Images/DSC_3956.JPG
  cogs/tgg/Assets/Images/DSC_4015.JPG
  cogs/tgg/Assets/Images/DSC_4573.JPG
  cogs/tgg/Assets/Images/IMG_0639.PNG
  cogs/tgg/Assets/Images/IMG_0641.PNG
  cogs/tgg/Assets/Images/IMG_0642.PNG
  cogs/tgg/Assets/Images/IMG_1608-removebg-preview.png
  cogs/tgg/Assets/Images/IMG_4D5DD8F95DA1-1.jpeg
  cogs/tgg/Assets/Images/Screenshot 2020-11-12 at 10.03.16.png
  cogs/tgg/Assets/Images/Screenshot 2020-11-12 at 10.03.33.png
  cogs/tgg/Assets/Images/Screenshot 2020-11-12 at 13.47.15.png
  cogs/tgg/Assets/Quote.json
  cogs/tgg/cog.py
  requirements.txt
Labels: enhancement

#36 corrected Calendar week view
  .gitignore
  cogs/calendar/util.py
Labels: enhancement

#37 Added bastos cog for free advertising.
  cogs/__init__.py
  cogs/bastos.py
  main.py
Labels: enhancement

#38 📆 offset
  cogs/calendar/Assets/.gitkeep
  cogs/calendar/cog.py
  cogs/calendar/util.py
  embed.py
Labels: documentation, enhancement

#40 Closes #39
  cogs/calendar/cog.py
  cogs/calendar/util.py
Labels: bug
